### ISSUE TITLE
Serialization : ~ appears after export/import as ~|

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#111]
Title. When a ~ is somewhere in a profile, upon exporting then importing the profile, it appears as ~| (although already having ~| seems not to add another pipe).

This issue already popped up earlier in Extended (as a ~= condition was changed to ~|= upon export/import, breaking the condition). Managed to track down the commit that solved it at the time for creations : https://github.com/kajisensei/Total-RP-3-Extended/commit/df6431684717b5b93dd980706fd8e34ff148defe

Might be something to look at directly in the deserialize function ?

**Comment by Ellypse** [comment]
Technical notes:
The `~`character is used as a special delimiter by the serializer, that's why a ~ in a serialized text is escaped as `~|` .  
The actual issue here is that the `|` character is a special character for texts in WoW. When pasting/entering text inside an editbox, to avoid interpreting the `|` the UI actually escape the character automatically, making it `||` when doing a `:GetText()`. The issue is not in the serialization functions itself but instead it should be handled when setting or getting text from the UI (like it is done in Kaji's commit).
