### ISSUE TITLE
Map markers for characters not using the right icon

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#120]
### What steps will reproduce the problem?
Scan for player stashes in Stormwind, then scan for characters.

### What is the expected output? What do you see instead?
Expected : a lot of points
Instead : a bunch of points and a bunch of stash icons (Extended stash icons are broken, disregard the style)
![image](https://user-images.githubusercontent.com/17127080/39666764-56eed768-50a9-11e8-917e-725b49e8fcc9.png)

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Obviously not without Extended, disabled everything else

### What version of Total RP 3 are you using?
1.3.4.1

### Was it working in a previous version? If yes, which was the last good one?
No clue when it last worked, but fairly sure it did at some point.

**Comment by Meorawr** [comment]
Technically it's an extended bug coupled with the change I made for coloring the blips.

I'd changed the [map blip decoration code](https://github.com/Ellypse/Total-RP-3/blob/master/totalRP3/modules/map/map_markers.lua#L218) from using `SetTexture` plus hardcoded constants for the texcoords to using Blizzard's texture atlasing system, which effectively maps a fixed string to a texture/texcoord pair.

In extended you're [plugging in pure texture coordinates](https://github.com/Ellypse/Total-RP-3-Extended/blob/master/totalRP3_Extended/inventory/inventory_drop.lua#L115) without ever changing out the texture.

There's a list of atlas mappings extracted with some black magic sorcery [here](https://www.townlong-yak.com/framexml/live/Helix/AtlasInfo.lua).

This causes issues because before TRP was using `Interface\Minimap\ObjectIcons.blp` as the [texture and the coordinates were relative to that](
https://github.com/Ellypse/Total-RP-3/commit/b0d8f48612140dddb896da5cce7e76b3bbfd8891#diff-28c81418b8b05e6dc345d87f84b679dfR217), but the atlas stuff now actually maps to `Interface\Minimap\ObjectIconsAtlas.blp`, which has wildly different texcoords.

Extended is mostly at fault here however because it wasn't explicitly setting the texture at any point, so it should have broken in a similar way should the map have recycled a point that previously belonged to a `HOUSE` decoration type. The scan marker decorator callback should either set `marker.iconAtlas` to an atlas which maps to the correct icon you're trying to display, or you can cheat and just add in a `marker.icon:SetTexture()` call.

**Comment by Solanya** [comment]
I figured it was due to your changes but couldn't understand where it was going wrong. That should actually make it much easier to fix, thanks ^^
